let firstName = prompt('Enter your first name.');
let lastName = prompt('Enter your last name.');
alert('Hey ' + firstName + ' ' + lastName + ' it is really great to meet you!');
let age = prompt('How old are you?');
alert('Ok');
let favouriteColour = prompt('What is your favourite colour?');
alert('Nice');
let favouriteAnimal = prompt('What is your favourite animal?');
alert('Same');
let pet = prompt('Do you have any pets?');
alert('Ok')
